remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: contrast


title: Aiden Van Greuning
description: Biomedical Engineering Portfolio

url: "https://aiden-vangreuning.github.io"
baseurl: "/aiden-vangreuning"

plugins:
  - jekyll-include-cache

header_pages:
  - index.md
  - projects.md
